[package]
name = "tab-portal"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
askama = "0.12.0"
axum = "0.6.18"
serde = "1.0.171"
shuttle-axum = "0.21.0"
shuttle-runtime = "0.21.0"
shuttle-secrets = "0.21.0"
shuttle-shared-db = { version = "0.21.0", features = ["postgres-rustls"] }
shuttle-static-folder = "0.21.0"
sqlx = { version = "0.6.3", features = ["postgres", "runtime-tokio-rustls", "uuid"] }
tokio = "1.29.1"
tower-http = { version = "0.4.1", features = ["fs"] }
ulid = { version = "1.0.0", features = ["serde", "uuid"] }
