name: Shuttle deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: cargo -V
      - run: rustup -V
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
